//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Table
    {
        public Category_Table()
        {
            this.Product_Table = new HashSet<Product_Table>();
        }
    
        public int Catagory_ID { get; set; }
        public string Catagory_Name { get; set; }
        public string Catagory_Description { get; set; }
        public int Catagory_Exist { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual ICollection<Product_Table> Product_Table { get; set; }
    }
}
