//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cus_Sup_Table
    {
        public Cus_Sup_Table()
        {
            this.Order_Retern_Table = new HashSet<Order_Retern_Table>();
            this.Order_Table = new HashSet<Order_Table>();
            this.Patient_Table = new HashSet<Patient_Table>();
            this.Purch_Retern_Table = new HashSet<Purch_Retern_Table>();
        }
    
        public int Cus_Sup_ID { get; set; }
        public string Cus_Sup_Mobile { get; set; }
        public string Cus_Sup_Name { get; set; }
        public string Cus_Sup_Company { get; set; }
        public string Cus_Sup_Email { get; set; }
        public string Cus_Sup_Notes { get; set; }
        public Nullable<decimal> Cus_Sup_Account { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual ICollection<Order_Retern_Table> Order_Retern_Table { get; set; }
        public virtual ICollection<Order_Table> Order_Table { get; set; }
        public virtual ICollection<Patient_Table> Patient_Table { get; set; }
        public virtual ICollection<Purch_Retern_Table> Purch_Retern_Table { get; set; }
    }
}
