//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lenses_Size_Table
    {
        public int Lenses_SizeID { get; set; }
        public int Patient_ID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<System.DateTime> Recive_Date { get; set; }
        public Nullable<decimal> Lenses_Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Pauid { get; set; }
        public Nullable<decimal> Reminng { get; set; }
        public string LS { get; set; }
        public string LC { get; set; }
        public string LX { get; set; }
        public string RS { get; set; }
        public string RC { get; set; }
        public string RX { get; set; }
    
        public virtual Patient_Table Patient_Table { get; set; }
    }
}
