//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_DBEntities : DbContext
    {
        public Project_DBEntities()
            : base("name=Project_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<Company_Info_Table> Company_Info_Table { get; set; }
        public virtual DbSet<Cus_Sup_Table> Cus_Sup_Table { get; set; }
        public virtual DbSet<Lenses_Size_Table> Lenses_Size_Table { get; set; }
        public virtual DbSet<Order_Details_Table> Order_Details_Table { get; set; }
        public virtual DbSet<Order_Retern_Details_Table> Order_Retern_Details_Table { get; set; }
        public virtual DbSet<Order_Retern_Table> Order_Retern_Table { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<Patient_Table> Patient_Table { get; set; }
        public virtual DbSet<Pay_Rev_Table> Pay_Rev_Table { get; set; }
        public virtual DbSet<Pay_Rev_Type_Table> Pay_Rev_Type_Table { get; set; }
        public virtual DbSet<Payback_Order_Retern_Table> Payback_Order_Retern_Table { get; set; }
        public virtual DbSet<Payback_Order_Table> Payback_Order_Table { get; set; }
        public virtual DbSet<Payback_Purch_Retern_Table> Payback_Purch_Retern_Table { get; set; }
        public virtual DbSet<PayBack_Purchases_Table> PayBack_Purchases_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<Purch_Retern_Details_Table> Purch_Retern_Details_Table { get; set; }
        public virtual DbSet<Purch_Retern_Table> Purch_Retern_Table { get; set; }
        public virtual DbSet<Purchases_Details_Table> Purchases_Details_Table { get; set; }
        public virtual DbSet<Purchases_Table> Purchases_Table { get; set; }
        public virtual DbSet<Safe_Table> Safe_Table { get; set; }
        public virtual DbSet<Stock_Purch_Table> Stock_Purch_Table { get; set; }
        public virtual DbSet<Stock_Quantity_Table> Stock_Quantity_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<System_Users_Table> System_Users_Table { get; set; }
        public virtual DbSet<Unite_Table> Unite_Table { get; set; }
    }
}
