//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Retern_Table
    {
        public Order_Retern_Table()
        {
            this.Order_Retern_Details_Table = new HashSet<Order_Retern_Details_Table>();
            this.Payback_Order_Retern_Table = new HashSet<Payback_Order_Retern_Table>();
        }
    
        public int Order_Retern_ID { get; set; }
        public string Order_Payment_Method { get; set; }
        public string Client_or_Not { get; set; }
        public System.DateTime Retern_Date { get; set; }
        public string Cus_Sup_Mobile { get; set; }
        public decimal Retern_Total { get; set; }
        public decimal Retern_Pauid { get; set; }
        public decimal Retern_Reming { get; set; }
        public string Reterns_Notes { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Cus_Sup_Table Cus_Sup_Table { get; set; }
        public virtual ICollection<Order_Retern_Details_Table> Order_Retern_Details_Table { get; set; }
        public virtual ICollection<Payback_Order_Retern_Table> Payback_Order_Retern_Table { get; set; }
    }
}
