//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Table
    {
        public Patient_Table()
        {
            this.Lenses_Size_Table = new HashSet<Lenses_Size_Table>();
        }
    
        public int Patient_ID { get; set; }
        public string Patient_Mobile { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Address { get; set; }
        public string Cus_Sup_Mobile { get; set; }
    
        public virtual Cus_Sup_Table Cus_Sup_Table { get; set; }
        public virtual ICollection<Lenses_Size_Table> Lenses_Size_Table { get; set; }
    }
}
