//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Rev_Table
    {
        public int Pay_Rev_ID { get; set; }
        public decimal Pay_Rev_Amount { get; set; }
        public System.DateTime Pay_Rev_Date { get; set; }
        public string Pay_Rev_Description { get; set; }
        public Nullable<int> Pay_Rev_Type_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Pay_Rev_Type_Table Pay_Rev_Type_Table { get; set; }
    }
}
