//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Rev_Type_Table
    {
        public Pay_Rev_Type_Table()
        {
            this.Pay_Rev_Table = new HashSet<Pay_Rev_Table>();
        }
    
        public int Pay_Rev_Type_ID { get; set; }
        public string Pay_Rev_Type_Name { get; set; }
        public string Pay_Rev_Type_Description { get; set; }
        public string Flag { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual ICollection<Pay_Rev_Table> Pay_Rev_Table { get; set; }
    }
}
