//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payback_Purch_Retern_Table
    {
        public int PayBack_Purch_Retern_ID { get; set; }
        public int Purch_Retern_ID { get; set; }
        public decimal PayBack_Purch_Retern_Value { get; set; }
        public System.DateTime PayBack_Purch_Retern_Date { get; set; }
        public decimal Last_Reming { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Purch_Retern_Table Purch_Retern_Table { get; set; }
    }
}
