//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payback_Order_Table
    {
        public int Payback_Order_ID { get; set; }
        public int Order_ID { get; set; }
        public decimal Payback_Value { get; set; }
        public System.DateTime Payback_Date { get; set; }
        public decimal Last_Reming { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> PayBackFlag { get; set; }
    
        public virtual Order_Table Order_Table { get; set; }
    }
}
