//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public Product_Table()
        {
            this.Order_Details_Table = new HashSet<Order_Details_Table>();
            this.Order_Retern_Details_Table = new HashSet<Order_Retern_Details_Table>();
            this.Purchases_Details_Table = new HashSet<Purchases_Details_Table>();
            this.Stock_Purch_Table = new HashSet<Stock_Purch_Table>();
            this.Stock_Quantity_Table = new HashSet<Stock_Quantity_Table>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public string BareCode { get; set; }
        public int Catagory_ID { get; set; }
        public Nullable<int> Unite_ID { get; set; }
        public string Description { get; set; }
        public int Product_Exist { get; set; }
        public string Product_Image { get; set; }
        public Nullable<int> AlarmQuantity { get; set; }
        public string Product_Size { get; set; }
        public string SProduct_ID { get; set; }
        public string SQuantity { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
        public virtual ICollection<Order_Details_Table> Order_Details_Table { get; set; }
        public virtual ICollection<Order_Retern_Details_Table> Order_Retern_Details_Table { get; set; }
        public virtual Unite_Table Unite_Table { get; set; }
        public virtual ICollection<Purchases_Details_Table> Purchases_Details_Table { get; set; }
        public virtual ICollection<Stock_Purch_Table> Stock_Purch_Table { get; set; }
        public virtual ICollection<Stock_Quantity_Table> Stock_Quantity_Table { get; set; }
    }
}
