//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases_Table
    {
        public Purchases_Table()
        {
            this.PayBack_Purchases_Table = new HashSet<PayBack_Purchases_Table>();
            this.Purchases_Details_Table = new HashSet<Purchases_Details_Table>();
            this.Stock_Purch_Table = new HashSet<Stock_Purch_Table>();
        }
    
        public int Purchases_ID { get; set; }
        public System.DateTime Addation_Date { get; set; }
        public string Cus_Sup_Mobile { get; set; }
        public decimal Purch_Total { get; set; }
        public decimal Purch__Pauid { get; set; }
        public decimal Purch_Remin { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        public virtual ICollection<PayBack_Purchases_Table> PayBack_Purchases_Table { get; set; }
        public virtual ICollection<Purchases_Details_Table> Purchases_Details_Table { get; set; }
        public virtual ICollection<Stock_Purch_Table> Stock_Purch_Table { get; set; }
    }
}
