//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Safe_Table
    {
        public int Safe_ID { get; set; }
        public decimal Safe_Amount { get; set; }
        public System.DateTime Addation_Date { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
