//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Users_Table
    {
        public int ID { get; set; }
        public string Sys_Username { get; set; }
        public string Sys_Pass { get; set; }
        public string Sys_User_Permission { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string Sys_User_Imagr_Path { get; set; }
    }
}
